### ISSUE TITLE
Process Names bigger than 16 get cut off

### ISSUE THREAD

**Issue by LWSS** [Heep042/vmread#12]
Guess the longer name is somewhere else

**Comment by h33p** [comment]
Indeed it seems to be the case. I can not do any reverse engineering myself, but look around the windows kernel structures for more information. I am open to pull requests implementing an improved method of getting the names of processes.

**Comment by ghost** [comment]
i got around this with module names instead of process names (A module name is going to have the full name so do memcmp with your 16 bytes of the process name in a look for the modules

<img src="https://i.imgur.com/a0nkOUk.png"/>

as you can see on the left you have names cut off at 16, and on the right names surpassing 16 in length. (newest version of flush(my tool) has it working on both sides this is an old SS)


sorry bad english, from china with virus

**Comment by LWSS** [comment]
cool thanks for sharing

**Comment by h33p** [comment]
> i got around this with module names instead of process names (A module name is going to have the full name so do memcmp with your 16 bytes of the process name in a look for the modules
> 
> ![](https://camo.githubusercontent.com/e7ddfe2b4b34dd326dcb0b7989654e535e1fbffd/68747470733a2f2f692e696d6775722e636f6d2f61306e6b4f556b2e706e67)
> 
> as you can see on the left you have names cut off at 16, and on the right names surpassing 16 in length. (newest version of flush(my tool) has it working on both sides this is an old SS)
> 
> sorry bad english, from china with virus

Nice tool and a great solution! A way without memcmp would be to find the module with the same base address as the process.

**Comment by ghost** [comment]
smart! 

[link](https://git.hacks.ltd/xerox/flush/blob/master/flush/UserModeTabList.cpp#L62) <--- gunna fix this. 

you should add me on discord i like this project alot and use it for many many things! 

_xeroxz#7212

**Comment by h33p** [comment]
Fixed in https://github.com/Heep042/vmread/commit/3876c2450978cbd449861d9d971e7f96091fff5a
