### ISSUE TITLE
Support for modules of System process

### ISSUE THREAD

**Issue by FocuzJS** [Heep042/vmread#9]
I'm trying to get the exports for win32kbase.sys and I'm not sure the best route to take.

I've tried reusing existing methods for getting a module list on the System process and its size is always 0, any advice?

**Comment by h33p** [comment]
As far as I know windows has PsLoadedModuleList. That's all my knowledge so far, will have to do some digging.

**Comment by h33p** [comment]
Implemented in https://github.com/Heep042/vmread/commit/01799b69733983a8f0a4f49f0219dd8a8737590e. However, I am yet to add appropriate HLAPI interfacing. From testing I have had the same results as you did, with only a few modules having any exports. As it turns out, win32kbase.sys was simply not loaded inside the kernel space, but rather inside the userspace processes. That, most likely, was the reason the export generation failed. Not closing until HLAPI reaches feature parity.

**Comment by h33p** [comment]
HLAPI bits added in https://github.com/Heep042/vmread/commit/823551c8472db2ed060f5006efd3c4521fa79301.
